name: Fetch Jokes and Save to Google Sheets

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  fetch-jokes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch jokes and send to Google Sheets
        run: node send-jokes-to-google-sheets.js
