name: Fetch Jokes and Save to Google Sheets

on:
  schedule:
    - cron: "0 8 1,15 * *"  # Exécute à 8h00 le 1er et le 15 de chaque mois
    

jobs:
  fetch-jokes:
   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch jokes and send to Google Sheets
        env:
            JOKE_WEBHOOK_URL: ${{ secrets.JOKE_WEBHOOK_URL }}
        run: node send-jokes-to-google-sheets.js
